version: '3.4'

services:
  guestbook.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "5001:80"
      - "5000:443"
    volumes:
      - ${APPDATA}\Roaming\Microsoft\UserSecrets:/appdata/Microsoft/UserSecrets
      - ${APPDATA}\Roaming\ASP.NET\Https:/appdata/ASP.NET/Https

  guestbook.service:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      rabbitmq:
       condition: service_healthy
      sql-server:
       condition: service_started
  
  rabbitmq:
    image: rabbitmq:3-management
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq/mnesia

  sql-server:
    user: root
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Guestbook24app"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data

volumes:
   rabbitmqdata:
   dbdata: